local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0 #5.0
  publish_frequency: 5.0 #2.0 # Hz which the costmap will publish visualization information
  static_map: false 
  rolling_window: true # True means that the costmap will remain centered around the robot as the robot moves around the world
  width: 5.0 #m
  height: 5.0 #m
  resolution: 0.05 # Set equal to static map resolution
